# Generated by Django 4.1.7 on 2023-05-14 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_usercategory_category_subsriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subsriber',
        ),
        migrations.AddField(
            model_name='category',
            name='subsribers',
            field=models.ManyToManyField(blank=True, through='news.UserCategory', to=settings.AUTH_USER_MODEL),
        ),
    ]
