# Generated by Django 4.1.7 on 2023-05-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_category_subsriber_category_subsribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subsribers',
            new_name='subscribers',
        ),
    ]
