# Generated by Django 4.1.7 on 2023-03-26 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest', '0004_alter_post_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractuser',
            name='abstractbaseuser_ptr',
        ),
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AbstractBaseUser',
        ),
        migrations.DeleteModel(
            name='AbstractUser',
        ),
    ]
